import jsPDF from "jspdf";

export interface ReportData {
  generatedAt: string;
  summary: {
    totalUsers: number;
    totalJobs: number;
    totalApplications: number;
    totalRevenue: number;
  };
  userBreakdown: {
    recruiters: number;
    jobSeekers: number;
  };
}

/**
 * Export report as JSON format
 */
export const exportAsJSON = (report: ReportData) => {
  const dataStr = JSON.stringify(report, null, 2);
  const dataBlob = new Blob([dataStr], { type: "application/json" });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `admin-report-${Date.now()}.json`;
  link.click();
  URL.revokeObjectURL(url);
};

/**
 * Export report as TEXT format
 */
export const exportAsText = (report: ReportData) => {
  const textContent = `
========================================
ADMIN DASHBOARD REPORT
========================================
Generated: ${report.generatedAt}

SUMMARY STATISTICS
========================================
Total Users:           ${report.summary.totalUsers}
Active Jobs:           ${report.summary.totalJobs}
Applications:          ${report.summary.totalApplications}
Total Revenue:         ₹${report.summary.totalRevenue.toLocaleString()}

USER BREAKDOWN
========================================
Recruiters:            ${report.userBreakdown.recruiters}
Job Seekers:           ${report.userBreakdown.jobSeekers}

METRICS
========================================
Recruiter Percentage:  ${
    report.userBreakdown.recruiters +
      report.userBreakdown.jobSeekers >
    0
      ? (
          (report.userBreakdown.recruiters /
            (report.userBreakdown.recruiters +
              report.userBreakdown.jobSeekers)) *
          100
        ).toFixed(2)
      : 0
  }%
Job Seeker Percentage: ${
    report.userBreakdown.recruiters +
      report.userBreakdown.jobSeekers >
    0
      ? (
          (report.userBreakdown.jobSeekers /
            (report.userBreakdown.recruiters +
              report.userBreakdown.jobSeekers)) *
          100
        ).toFixed(2)
      : 0
  }%
Conversion Rate:       ${
    report.summary.totalJobs > 0
      ? (
          (report.summary.totalApplications /
            report.summary.totalJobs) *
          100
        ).toFixed(2)
      : 0
  }%

========================================
This report was auto-generated by Admin Dashboard
========================================
  `;

  const blob = new Blob([textContent], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `admin-report-${Date.now()}.txt`;
  link.click();
  URL.revokeObjectURL(url);
};

/**
 * Export report as PDF format
 */
export const exportAsPDF = (report: ReportData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Header
  doc.setFontSize(24);
  doc.text("Admin Dashboard Report", pageWidth / 2, yPosition, {
    align: "center",
  });
  yPosition += 12;

  // Generated Date
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text(`Generated: ${report.generatedAt}`, pageWidth / 2, yPosition, {
    align: "center",
  });
  yPosition += 15;

  // Summary Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text("Summary Statistics", 20, yPosition);
  yPosition += 10;

  doc.setFontSize(11);
  const summaryData = [
    `Total Users: ${report.summary.totalUsers}`,
    `Active Jobs: ${report.summary.totalJobs}`,
    `Applications: ${report.summary.totalApplications}`,
    `Total Revenue: Rs ${report.summary.totalRevenue.toLocaleString()}`,
  ];

  summaryData.forEach((line) => {
    doc.text(line, 25, yPosition);
    yPosition += 8;
  });

  yPosition += 8;

  // User Breakdown Section
  doc.setFontSize(14);
  doc.text("User Breakdown", 20, yPosition);
  yPosition += 10;

  doc.setFontSize(11);
  const totalUsers =
    report.userBreakdown.recruiters + report.userBreakdown.jobSeekers;
  const recruiterPercentage =
    totalUsers > 0
      ? ((report.userBreakdown.recruiters / totalUsers) * 100).toFixed(2)
      : 0;
  const jobSeekerPercentage =
    totalUsers > 0
      ? ((report.userBreakdown.jobSeekers / totalUsers) * 100).toFixed(2)
      : 0;

  const breakdownData = [
    `Recruiters: ${report.userBreakdown.recruiters} (${recruiterPercentage}%)`,
    `Job Seekers: ${report.userBreakdown.jobSeekers} (${jobSeekerPercentage}%)`,
  ];

  breakdownData.forEach((line) => {
    doc.text(line, 25, yPosition);
    yPosition += 8;
  });

  yPosition += 8;

  // Metrics Section
  doc.setFontSize(14);
  doc.text("Performance Metrics", 20, yPosition);
  yPosition += 10;

  doc.setFontSize(11);
  const conversionRate =
    report.summary.totalJobs > 0
      ? (
          (report.summary.totalApplications / report.summary.totalJobs) *
          100
        ).toFixed(2)
      : 0;

  const metricsData = [
    `Conversion Rate: ${conversionRate}%`,
    `Average Revenue per User: Rs ${(
      report.summary.totalRevenue / (report.summary.totalUsers || 1)
    ).toFixed(2)}`,
  ];

  metricsData.forEach((line) => {
    doc.text(line, 25, yPosition);
    yPosition += 8;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "This report was auto-generated by Admin Dashboard",
    20,
    pageHeight - 10
  );

  doc.save(`admin-report-${Date.now()}.pdf`);
};


/**
 * Generate all reports at once
 */
export const exportAllFormats = async (report: ReportData) => {
  try {
    // Export as JSON
    exportAsJSON(report);

    // Small delay to avoid issues
    await new Promise((resolve) => setTimeout(resolve, 300));

    // Export as Text
    exportAsText(report);

    await new Promise((resolve) => setTimeout(resolve, 300));

    // Export as PDF
    exportAsPDF(report);
  } catch (error) {
    throw error;
  }
};

/**
 * Generate specific format
 */
export const generateReport = (
  report: ReportData,
  format: "json" | "text" | "pdf" | "all"
) => {
  switch (format) {
    case "json":
      exportAsJSON(report);
      break;
    case "text":
      exportAsText(report);
      break;
    case "pdf":
      exportAsPDF(report);
      break;
    case "all":
      exportAllFormats(report);
      break;
    default:
      exportAsJSON(report);
  }
};
